#!/bin/bash
echo Installing basic utilities and python3
#sudo apt-get install -y man-db manpages manpages-dev
sudo apt-get install -y autoconf automake libtool
sudo apt-get install -y libncurses5-dev libfdt-dev
sudo apt-get install -y device-tree-compiler stress libpython3-dev
#sudo apt-get install -y arduino-mk arduino
sudo apt-get install -y git build-essential flex bison
sudo apt-get install -y swig3.0 nodejs-dev cmake pkg-config
sudo apt-get install -y libpcre3-dev v4l-utils abootimg
