#!/bin/bash
cd kernel

#get the initrd.img if necessary
if [ ! -f initrd.img ]; then
	wget https://snapshots.linaro.org/96boards/dragonboard410c/linaro/debian/latest/initrd.img-4.14.0-qcomlt-arm64
	mv initrd.img-4.14.0-qcomlt-arm64 initrd.img
fi

# get the skales tool if needed
if [ ! -d skales ]; then
	git clone git://codeaurora.org/quic/kernel/skales
fi

skales/dtbTool -o dt.img -s 4096 arch/arm64/boot/dts/qcom/
export CMDLINE="root=/dev/disk/by-partlabel/rootfs rw rootwait console=tty0 console=ttyMSM0,115200n8"
skales/mkbootimg --kernel kernel/arch/arm64/boot/Image \
               --ramdisk initrd.img \
               --output boot_db820c.img \
               --dt dt.img \
               --pagesize 4096 \
               --base 0x80000000 \
               --cmdline "${CMDLINE}";
