#!/bin/sh

# build bazel from source because there is no arm64 version prebuild
#sudo apt-get install -y build-essential openjdk-8-jdk python3 zip
#sudo apt-get install -y python3-numpy python3-dev python3-pip python3-wheel python-all-dev
#mkdir bazel-bootstrap
#cd bazel-bootstrap
#wget https://github.com/bazelbuild/bazel/releases/download/0.8.1/bazel-0.8.1-dist.zip
#unzip bazel-0.8.1-dist.zip
#export JAVA_OPTS="-Xms2046m -Xmx2048m"
#./compile.sh
#cp output/bazel ~/bin
#cd ..

# build tensorflow
#sudo apt-get install -y python-numpy python-dev python-pip python-wheel python-all-dev
sudo apt-get install -y python3-numpy python3-dev python3-pip python3-wheel python-all-dev
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
git checkout master
echo answer to the first configure option is "/usr/bin/python3"
echo Accept all of the defaults for the remaining configurationb questions
./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
bazel shutdown
sudo pip install /tmp/tensorflow_pkg/tensorflow-1.4.0-py2-none-any.whl
cd ..
